import Clickable from "components/ui/Clickable";
import H1 from "components/ui/H1";
import H2 from "components/ui/H2";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRive } from "@rive-app/react-canvas";
import { motion } from "framer-motion";

const contentVariants = {
  hidden: {
    opacity: 0,
    x: -20,
  },
  enter: {
    opacity: 1,
    x: 0,
    transition: {
      delay: 1.2,
      duration: 0.45,
      ease: "easeOut",
    },
  },
};

const Home: NextPage = () => {
  const { rive, RiveComponent } = useRive({
    src: "/rive/dial.riv",
    autoplay: false,
  });

  rive && rive.play("Enter");

  const onNext = () => {
    rive && rive.play("Previous");
  };
  const onForward = () => {
    rive && rive.play("Forward");
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="fixed top-0 flex w-screen justify-end p-6 text-dark">
        <Link href="/">
          <Clickable>Lets Talk</Clickable>
        </Link>
      </nav>
      <main className="relative flex h-screen w-screen items-center justify-start  bg-light text-dark">
        <div className="relative flex h-screen w-1/3">
          <RiveComponent onMouseDown={onNext} onDoubleClick={onForward} />
        </div>
        <motion.div
          className="ml-2 flex h-full  w-2/3 flex-col justify-between py-6"
          variants={contentVariants}
          animate="enter"
          initial="hidden"
        >
          <Clickable>Portfolio</Clickable>
          <div className="flex w-3/5 flex-col space-y-6">
            <H1>Noël Cserépy</H1>
            <H2>Frontend Developer & Designer</H2>
            <p>
              I design visually striking, unique web experiences. I portray my
              client’s vision in the best light using performant web pages.
            </p>
          </div>
          <Clickable>2023</Clickable>
        </motion.div>
      </main>
    </>
  );
};

export default Home;
