import Clickable from "components/ui/Clickable";
import H1 from "components/ui/H1";
import H2 from "components/ui/H2";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRive } from "@rive-app/react-canvas";
import { AnimatePresence, motion, useAnimationControls } from "framer-motion";
import { useEffect, useState } from "react";
import type { WheelEventHandler } from "react";
import data from "data";

const contentVariants = {
  hidden: {
    opacity: 0,
    x: -20,
  },
  enter: {
    opacity: 1,
    x: 0,
    transition: {
      delay: 1.2,
      duration: 0.45,
      ease: "easeOut",
    },
  },
  reEnter: {
    opacity: 1,
    x: 0,
    transition: {
      duration: 0.45,
      ease: "easeOut",
    },
  },
  exit: {
    opacity: 0,
    x: -20,
    transition: {
      duration: 0.2,
      ease: "easeIn",
    },
  },
};

const Home: NextPage = () => {
  const [scrollIndex, setScrollIndex] = useState(0);
  const [isScrolling, setIsScrolling] = useState(false);
  const [hasEntered, setHasEntered] = useState(false);
  const controls = useAnimationControls();
  const { rive, RiveComponent } = useRive({
    src: "/rive/dial.riv",
    autoplay: false,
    onStop: () => {
      controls.start("reEnter").catch(console.error);
    },
  });

  if (!data) throw new Error("No data");

  const pagesLength = data.pages.length;

  if (!hasEntered) {
    rive && rive.play("Enter");
  }

  const onNext = () => {
    rive && rive.play("Next");
  };
  const onPrevious = () => {
    rive && rive.play("Previous");
  };
  const onForward = () => {
    rive && rive.play("Forward");
  };
  const onBack = () => {
    rive && rive.play("Back");
  };

  const onScroll = async (e: WheelEvent) => {
    if (isScrolling) return;
    setIsScrolling(true);
    setHasEntered(true);
    if (e.deltaY > 0) {
      if (scrollIndex === pagesLength - 1) {
        await controls.start("exit");
        setScrollIndex(0);
        onNext();
        return;
      }
      await controls.start("exit");
      setScrollIndex(scrollIndex + 1);
      onNext();
    }
    if (e.deltaY < 0) {
      if (scrollIndex === 0) {
        setScrollIndex(pagesLength - 1);
        onPrevious();
        return;
      }
      setScrollIndex(scrollIndex - 1);
      onPrevious();
    }
  };

  useEffect(() => {
    const timeout = setTimeout(() => {
      setIsScrolling(false);
    }, 700);
    return () => clearTimeout(timeout);
  }, [scrollIndex]);

  useEffect(() => {
    const startSequence = async () => {
      await controls.start("enter");
    };

    if (!hasEntered) {
      startSequence().catch(console.error);
      return;
    }
  }, [controls, hasEntered]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <nav className="fixed top-0 flex w-screen justify-end p-6 text-dark">
        <Link href="/">
          <Clickable>{`Let's Talk`}</Clickable>
        </Link>
      </nav>
      <main
        className="relative flex h-screen w-screen items-center justify-start bg-light text-dark"
        onWheel={onScroll as unknown as WheelEventHandler<HTMLDivElement>}
      >
        <div className="relative flex aspect-1/2 h-screen">
          <RiveComponent />
        </div>

        <AnimatePresence mode="wait">
          {data.pages.map((page, index) => {
            if (index === scrollIndex)
              return (
                <motion.div
                  key={page.title}
                  className="ml-2 flex h-[92%]  w-2/3 flex-col justify-between"
                  variants={contentVariants}
                  animate={controls}
                  initial="hidden"
                  exit="exit"
                >
                  <Clickable>{page.header}</Clickable>
                  <div className="flex w-3/5 flex-col space-y-6">
                    <H1>{page.title}</H1>
                    <H2>{page.subtitle}</H2>
                    <p>{page.desciption}</p>
                  </div>
                  <Clickable>{page.date}</Clickable>
                </motion.div>
              );
          })}
        </AnimatePresence>
      </main>
    </>
  );
};

export default Home;
